from pathlib import Path
import re, sys, json
ROOT = Path(__file__).resolve().parents[1]
errors=[]
def require(value,message):
    if not value: errors.append(message)
index=(ROOT/'index.html').read_text(encoding='utf-8')
config=(ROOT/'config.js').read_text(encoding='utf-8')
app=(ROOT/'app.js').read_text(encoding='utf-8')
guest=(ROOT/'guest-utils.js').read_text(encoding='utf-8')
backend=(ROOT/'tools/wedding-wishes-webapp.gs').read_text(encoding='utf-8')
package=json.loads((ROOT/'package.json').read_text(encoding='utf-8'))
lock=json.loads((ROOT/'package-lock.json').read_text(encoding='utf-8'))
require('v19.4-20260724' in index,'sai build marker')
require(package['version'] == lock['version'] == lock['packages']['']['version'],'package-lock lệch package.json')
for event_id in ['bride','groom','nhatrang','saigon']:
    require(f'{event_id}: {{' in config,f'thiếu event {event_id}')
require('eventContext' in config,'thiếu event context')
require('eventsParameter: "events"' in config,'thiếu events parameter')
require('buildInvitationUrl' in guest,'thiếu URL helper đa sự kiện')
require('buildEventEntryUrl' in guest,'thiếu event share entry helper')
require('setupEventSwitcher' in app,'thiếu event switcher logic')
require('renderEventTimeline' in app,'thiếu dynamic timeline')
require('id="eventSwitcher"' in index,'thiếu event switcher DOM')
require('id="eventTimeline"' in index,'thiếu timeline DOM')
require('id="invitationCover"' in index,'thiếu cover dialog')
require('id="coverOpenButton"' in index,'thiếu nút mở cover')
require('id="storyPlayer"' in index and 'id="storyButton"' in index,'thiếu story controller')
require('setupOpeningExperience' in app,'thiếu opening experience logic')
require('setupAttendanceContactDialog' in app,'thiếu RSVP contact fallback')
require('getAdaptiveDataState' in app,'thiếu adaptive data mode')
require('id="attendanceContactDialog"' in index,'thiếu attendance contact dialog')
require('id="coverDataHint"' in index,'thiếu data saver hint')
require((ROOT/'tools/guest-list-template.csv').exists(),'thiếu guest CSV template')
require('setupGuidedStory' in app,'thiếu guided story logic')
require('prepareStoryAssets' in app,'thiếu story asset preloading')
require('pausedByVisibility' in app,'thiếu pause audio khi tab ẩn')
require('id="coverSimpleButton"' in index,'thiếu simple mode')
require('id="storyPreviousButton"' in index and 'id="storyNextButton"' in index,'thiếu điều hướng chapter')
require('data-story-title' in index,'thiếu tên chapter')
require('data-story-chapter aria-live="polite"' in index,'story chapter thiếu aria-live')
require('sharing: {\n          title: "Tiệc Báo Hỷ Nha Trang' in config,'sharing Nha Trang bị lồng sai')
require('openingExperience:' in config,'thiếu opening config')
require('prefers-reduced-motion: reduce' in (ROOT/'assets/css/wedding-motion.css').read_text(encoding='utf-8'),'thiếu reduced motion')
require('guestLead' in config and 'eventName' in config,'thiếu copy theo event')
require('mapsUrl: ""' in config,'draft maps phải có trạng thái disabled')
require('rsvp: { enabled: false' in config,'RSVP cũ chưa bị vô hiệu hóa an toàn')
require((ROOT/'tools/create-google-forms-rsvp-multi-event.gs').exists(),'thiếu Form builder')
require((ROOT/'MULTI-EVENT-SETUP.md').exists(),'thiếu setup doc')
require((ROOT/'event-entry.js').exists(),'thiếu event-entry.js')
require('events/${encodeURIComponent(activeEventId)}/' in (ROOT/'tools/create-guest-links.html').read_text(encoding='utf-8'),'guest link generator chưa dùng event entry page')
require('payload.ok && payload.stored === true' in app,'wishes contract bị mất')
require('duplicateWindowSeconds: 21600' in backend,'cache TTL sai')
require('innerHTML' not in app,'app.js không được dùng innerHTML')
require('innerHTML' not in guest,'guest-utils không được dùng innerHTML')
require(len(re.findall(r'\bid="([^"]+)"',index))==len(set(re.findall(r'\bid="([^"]+)"',index))),'HTML ID trùng')
for path in ['tiec-cuoi-nha-gai-2026-07-29.ics','le-thanh-hon-nha-trai-2026-07-30.ics','bao-hy-nha-trang-2026-08-15.ics','bao-hy-sai-gon-2026-08-22.ics']:
    require((ROOT/'assets/calendar'/path).exists(),f'thiếu {path}')
if errors:
    print('FAIL')
    for error in errors: print('-',error)
    sys.exit(1)
print('PASS: v19 multi-event release checks')
